org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true -Dsun.net.inetaddr.negative.ttl=0
org.gradle.configuration-cache=false
org.gradle.caching=true
org.gradle.workers.max=4
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
WISHTRACE_GOOGLE_WEB_CLIENT_ID=301373407398-80krj64h4l2d8c70hchvsln5mhkrknhl.apps.googleusercontent.com
WISHTRACE_SANDBOX_TOOLS=true
